### ISSUE TITLE
CookieJar - TypeError: Cannot read property 'secure' of undefined

### ISSUE THREAD

**Issue by SamuelMarks** [cozy/request-json#30]
Unfortunately I cannot use jar effectively between clients. Thanks for any advice on how to get this working.

Test case:
========
```
request     = require 'request'
requestJson = require 'request-json'

jar         = request.jar()
client1     = requestJson.newClient 'http://localhost:3021', jar: jar

user        = email: 'foo@bar.com', password: 'password'

client0.post '/register', user, (err, res, body) ->
    console.log "%j, %j, %j", err, res, body

client0.post '/login', user, (err, res, body) ->
    console.log "%j, %j, %j", err, res, body

client1     = requestJson.newClient 'http://localhost:3020', jar: jar

# Error thrown below this line:
client1.get '/profile', (err, res, body) ->
    console.log "%j, %j, %j", err, res, body    
```

Traceback:
========
```
TypeError: Cannot read property 'secure' of undefined
at CookieJar.getCookies (node_modules/request/node_modules/tough-cookie/lib/cookie.js:946:23)
    at CookieJar.getCookieString (node_modules/request/node_modules/tough-cookie/lib/cookie.js:1044:19)
    at Request.jar (node_modules/request-json/node_modules/request/request.js:1277:33)
    at Request.init (node_modules/request-json/node_modules/request/request.js:202:8)
    at new Request (node_modules/request-json/node_modules/request/request.js:97:8)
    at request (node_modules/request-json/node_modules/request/index.js:50:11)
    at JsonClient.exports.JsonClient.JsonClient.get (node_modules/request-json/main.js:105:14)
```

EDIT: Just wrote up this tiny wrapper of the `request` library which works just fine for my use-cases:
```
request = require 'request'

module.exports = (base='', jar=null) -> (method, route, payload=null) -> (cb) ->
    options =
        url: "#{base}#{route}"
        json: payload ? true
        jar: jar ? request.jar()
        method: method
    request options, (err, res, body) ->
        cb err, res, body
```

**Comment by frankrousseau** [comment]
No news since three months. I close the issue.
