### ISSUE TITLE
Does't support header gzip

### ISSUE THREAD

**Issue by wangbinxiang** [cozy/request-json#58]
I set 
`client.headers['Accept-Encoding'] = 'gzip';`
and I get error
`error occured: Error: Parsing error : Unexpected token  in JSON at position 0, body=
(�ZKo�8��W>]`����"h�{�CoqI���!�Q�[��/)Ŷ$ӱ��yU�aМ9Cg>��ק���]�'_N~5������B��M�,[�[���4+ʆw����t�M�y�~��E=�
 w�����]�6ٞ~=�at��:��
                    Q�EB���y��������4�U���KW�m�/�
                                                 �岨.@fOs}���<q�����?w}�&]�[��s2�s��2M���9E�}zKnucW�٘H�%��܅Y�tg�zfUm�/��7e��X��i�<�1e}!ܷ��T�ThVTFU�2�ga����y�#�+w�,~n�t{
��ꢑZ[]�26�ly�l,(� �,6P�-H�ӀA��P�Y�b�̳�?Ef�\�3����=��v/�u�)��ʖ���בa�Y��vQ� �Nj�{�q߲f+��2IhLXS��;����*��19�8��k9�;���#+�d��k�� ����<��,�a���l�����lV��
Έ��81�I輸{zK�A�S=�����x��:B>�Sc��\^^��*��o���}��-��c��~ �X��C��p�D NH��P̉�d)ۃb�
                                                                              /
                                                                               aA�	�a��H���@X�������#��`�����a�� ,}��z
,������[&������z<OC��Q�Q�Ջ����q����y��qߣ=��T-���rh�X�U
�c
C���e!c�����3�0P�W�A��M�r��9�@YH��wl�1׻����ޭ⟠G��y�2㩇�S��cdC��W�BeKy��R
                                                                      ��+
ME�d��,I}��%�E��vZ+m��~���=�Q�x2,v�WB&�kO

U데�r�p�}f�󄶁M��g��f�8����38����`F F����@
                                        ��p�5�ChO��Wu���^�p|h�.��#����åg���2֞׸�7�=����x<�Y"�����I�}r��T��A^��S���1�bdf�	�h
          (��GfĀN�%�$C����:W�f������x�،�����TA�3���c�x-lx�,�n>����պ͕��u�����23-
    at Object.parseBody (/Users/wangbinxiang/nodejs/SaasSubAdminFrontEnd/node_modules/request-json/main.js:67:19)
    at Request._callback (/Users/wangbinxiang/nodejs/SaasSubAdminFrontEnd/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/Users/wangbinxiang/nodejs/SaasSubAdminFrontEnd/node_modules/request-json/node_modules/request/request.js:187:22)`

Can your support gzip?

**Comment by clochix** [comment]
Hello @wangbinxiang,

This library was used by the server part of CozyCloud, but we are now [migrating it from Node.js to Go](https://blog.cozycloud.cc/post/2016/11/21/On-the-road-to-Cozy-version-3), and don't use it anymore.
So I fear we won't have time to had features to this module. Sorry for that.

**Comment by frankrousseau** [comment]
@wangbinxiang Can you provide a snippet? 

@clochix If you don't use it anymore I'm interested in taking back the ownership of the repo on NPM. There is still 30k downloads a month. So, I would be glad to maintain it.

**Comment by wangbinxiang** [comment]
@frankrousseau just set 
`client.headers['Accept-Encoding'] = 'gzip';`
and jsonapi server send gziped body

**Comment by clochix** [comment]
Hello @frankrousseau,
We are really glad you propose to help this library survive our pivot away from Node.
We need to discuss internally to decide how to transfer to you the ownership, but this definitively looks like an awesome idea! Thanks!!

**Comment by frankrousseau** [comment]
Ok cool. Let me know what you decide. Wathever I will look at the problem of @wangbinxiang.
